name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        yarn --cwd website --frozen-lockfile

    - name: Publish
      env:
        GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
        GITHUB_EMAIL: ${{ secrets.DEPLOY_GITHUB_EMAIL }}
        GITHUB_USER: ${{ secrets.DEPLOY_GITHUB_USER }}
      run: |
        git config --global user.email "$GITHUB_EMAIL"
        git config --global user.name "$GITHUB_USER"
        echo "machine github.com login $GITHUB_USER password $GITHUB_TOKEN" > ~/.netrc
        yarn gh-pages
